# Glossary

***Boolean operators***: In literature searches, Boolean operators are specific words (**AND**, **OR** and **NOT)** used to combine or exclude search terms. They improve the relevance of search results.

***Eligibility criteria***: In evidence synthesis, eligibility criteria are the rules applied to decide which studies to include or exclude.

***Evidence synthesis:*** This is the systematic process of gathering information from various sources and disciplines to inform discussions and decisions on specific issues.

***GRADE*** ***Framework:***  The GRADE framework, which stands for ***Grading of Recommendations, Assessment, Development, and Evaluations***, is globally adopted framework for evaluating the certainty of the conclusions drawn from a body of research evidence. It is widely used by both guideline developers and systematic reviewers.

***Medical Subject Headings (MeSH):*** These are standardised terms used by the U.S. National Library of Medicine to index medical articles in databases like Medline. Using MeSH terms facilitates precise searches for specific health topics.

***PICO framework:***  Systematic reviewers often use the PICO framework to formulate review questions about the effectiveness of interventions. PICO is an acronym of the key elements of an effectiveness question. PICO stands for ***P***articipants, ***I***nterventions, ***C***omparators, and ***O***utcomes.

***Risk of bias:***  This relates to the likelihood that the design or conduct of a study will produce biased (or misleading) results and influence our confidence in the results of individual studies and a body of related research evidence.

***Search filters***: In evidence synthesis, a search filter is a pre-defined combination of search terms. Well-established search filters often have been validated by experts and can optimise literature retrieval based on specific criteria. [ISSG Search Filters Resource](https://sites.google.com/a/york.ac.uk/issg-search-filters-resource/home) has a collection of established search filters on various topics.

***Truncation and Wildcards:***  Truncation involves using a symbol at the end of a term to find all variations of that term. For example, "surg\*" retrieves 'surgery' and 'surgical.' Wildcards replace a single letter in a word to retrieve relevant variations of the same word; for instance, "p?diatric" can retrieve both 'pediatric' and 'paediatric’.
