# An Introduction to Rapid Evidence Synthesis

## Learning objectives

By the end of this section you should:

·       Understand how the NIHR Applied Research Collaboration Greater Manchester (ARC-GM) approach to rapid evidence synthesis (RES) compares with other evidence synthesis approaches e.g., systematic and rapid reviews;

·       Have an overview of the key steps in producing a RES;

·       Consider situations when generating a RES is feasible and useful.

## Overview of evidence synthesis approaches

In health and care systems, an **innovation** is any intentional change in the provision of health or social care e.g.,

-   a new treatment,

-   new health technology system,

-   new test,

-   new public health policy or programme, or

-   a change in working method.

Health and social care organisations make decisions to adopt and implement new innovations all the time. Inherent in an adoption decision are considerations of effectiveness (this change is going to make a positive difference), cost (the cost of this change will be worthwhile) and safety (this change is unlikely to harm service users, patients, staff or the wider system). The kind of evidence that assists this kind of adoption decision includes existing, relevant research evidence and it needs to be synthesised to be given due consideration.

*‘Evidence synthesis refers to the process of bringing together information from a range of sources and disciplines to inform debates and decisions on specific issues. Decision-making and public debate are best served if policymakers have access to the best current evidence on an issue. An accurate, concise and unbiased synthesis of the evidence is therefore one of the most valuable contributions the research community can offer policymakers.’*

From ‘***Evidence synthesis for policy: a statement of principles**’by the Royal Society and the Academy of Medical Sciences* \[5\].

Of the available evidence synthesis approaches, systematic review and rapid reviews are commonly used.

‘*Systematic reviews seek to collate evidence that fits pre-specified eligibility criteria in order to answer a specific research question. They aim to minimize bias by using explicit, systematic methods documented in advance with a protocol.*’

From ***Cochrane Handbook for Systematic Reviews of Interventions \[6\].***

See the introductory video produced by the Cochrane Collaboration on [What are systematic reviews?](https://www.youtube.com/watch?v=egJlW4vkb1Y&t=29s)

Systematic reviews are widely acknowledged to be the gold standard approach to summarising and synthesising research findings. Reviewers follow a pre-specified protocol (or plan), conduct an exhaustive and comprehensive search to find research relevant to a well-defined question, and then appraise the risk of bias in eligible studies before synthesis (@nte-1). The risk of bias assessment ensures that the results of the research are interpreted in the light of how well the research was done and how likely the apparent results are to be ‘true.’

Conducting systematic reviews is, however, often a lengthy process. A Cochrane review takes, on average, approximately 23 months to produce \[7\]. Rapid reviews emerged to address this issue, adapting systematic review methodology ‘*that accelerates the process of conducting a traditional systematic review through streamlining or omitting specific methods to produce evidence for stakeholders in a resource-efficient manner*’\[8\]. So, whilst the key steps in a systematic review are common to rapid approaches to systematic reviews (@nte-1), certain elements are curtailed. Changes include searches being limited to a specific time period and reviewers conducting informal critical appraisal and quality assessment. Even with these modifications, rapid reviews can still take months to deliver.

::: {#nte-1 .callout-note}
## Common steps in a systematic and rapid review

• Clearly define the question that the review is asking of the existing research, including a clear definition and understanding the relevant innovation

• Outline a protocol or plan for the review

• Search for potentially relevant research

• Select the relevant research that can answer the question, using the inclusion criteria in the protocol

• Extract relevant data from the research and appraise its risk of bias (likely validity of the results)

• Summarise and interpret the available research evidence
:::

The time it takes for systematic reviews (and rapid versions of these) to come to fruition can prevent important research findings from reaching decision-makers when they need them.  Decision-makers in health and care services often need insights from evidence in weeks rather than months or years to inform decisions on scaling up (or scaling down) innovations. The lack of suitable rapid evidence synthesis methods often leads to research evidence being disregarded during decision and policy making. This situation led us to develop our rapid approach which, whilst imperfect, ensures that existing research evidence is part of the process.

## The ARC-GM Rapid Evidence Synthesis (RES) process

The ARC-GM RES approach generates evidence-informed insights for decision-makers rapidly, aiming to accelerate patient and public access to beneficial innovations. A RES can be used to help decision-making on the adoption of all types of innovations used in the context of the health and care system; whether this is to improve treatment, diagnosis, education, outreach, prevention or research purposes, with the long-term goals of improving quality, safety, outcomes, efficiency and costs.

The RES process follows the steps outlined in @nte-1 but uses an approach that can be completed in weeks rather than months or years.

RES are designed to produce a ‘good-enough’ (rather than perfect) summary of the evidence to support decision-making in a short timeframe, where the alternative might be not using research at all. This approach focuses on delivering a concise and up-to-date synthesis of the most relevant and methodologically robust evidence available. In our own practice, we often prioritise summarising pre-appraised evidence for a RES. While not exhaustive, the RES ensures that uncertainties are clearly identified and acknowledged.

Key considerations when developing our RES approach include speed, transparency, an emphasis on the relevance of the evidence and analysis of its robustness and usability.

·       ***Speed***. By often prioritising and summarising existing, pre-appraised evidence synthesis in a brief report for decision-makers, our approach can deliver a RES in 2–8 weeks, depending on the size and scope of the motivating questions. The approach can be applied to complex innovations and considers where evidence for innovations may be sparse or of limited relevance.

·       ***Transparency and robustness***. The principles of the [GRADE Evidence to Decision framework](https://www.bmj.com/content/353/bmj.i2016) are central to the RES approach, which makes the RES, and the decision process to which it contributes, transparent, consistent and reproducible.

·       ***Relevance and usability***. The RES approach considers the relevance of the evidence to the local health and care system and context as well as its reliability.

## Deciding when to conduct a RES instead of other types of evidence synthesis

Whilst more rapid than most other evidence synthesis options, undertaking a RES is still resource intensive. You can use the following questions to help decide which RES requests are high priority and feasible:

::: {.callout-tip icon="false"}
·       How answerable is the question for a RES?  

·       How suitable is a RES and is there a better (evidence synthesis) approach to take? When considering the review approach the risk of getting the ‘wrong answer’ needs to be considered. What is the tolerance for decision-makers of drawing the wrong conclusion because the review approach increases the risk of missing key research?

·       How practical and feasible is it to complete a RES? Is there an existing evidence base for this area of inquiry?

·       How useful and impactful are the potential findings of a RES likely to be in relation to decisions to adopt innovations in local health and care systems?
:::

Whilst a RES is often the appropriate option in the context of knowledge mobilisation, in some cases it is not, and teams need to carefully assess whether other evidence synthesis products like systematic reviews are more appropriate. The decision pathway may help you determine which type of evidence synthesis is most appropriate to undertake.

RES focuses on ***knowledge mobilisation***—that is, summarising existing knowledge or evidence to share with specific audiences who need it for decision-making. When the goal of an evidence inquiry is to generate new knowledge, other types of evidence synthesis may be more appropriate.

Here is an example of a scenario where a RES is needed as a *knowledge mobilisation* product, rather than other types of reviews.

The Greater Manchester Integrated Care Partnership (GM ICP) Population Health team aimed to develop regional policies to restrict the advertising of harmful commodities in public sector–owned spaces and wanted to use research evidence to support their practice. To make timely and informed policy decisions, the team needed rapid access to existing research evidence on what similar regions had already implemented and the potential health and financial impacts of such restrictions.

In this context, the objective was **not** to generate new knowledge through a comprehensive and exhaustive review, but rather to **mobilise** the most relevant, accessible, and actionable evidence already available. Decision‑makers required a concise synthesis that could be produced quickly, highlight what is known, identify uncertainties, and support policy development within tight timelines. A RES was therefore the appropriate approach, offering a pragmatic and timely summary of the best available evidence to inform decision‑making. For a RES, evidence may come from existing systematic reviews, primary studies that have not yet been synthesised, and other relevant sources. The value of producing a RES, even when systematic reviews already exist, is that it translates the available evidence into a more accessible format, includes critical appraisal, and assesses how relevant the evidence is to the regional context so it can be made actionable.

## An overview of key steps when conducting a RES

Our RES process is intended to be flexible, allowing for a range of questions to be addressed and using various exploratory approaches. It takes a pragmatic approach that requires partner input for co-design and researcher judgement to refine the approach at each stage.

The RES approach consists of several steps, which will be explained in more detail in later sections. These steps are not necessarily linear but iterative. The RES process is captured in the example protocol in @nte-2.

::: {#nte-2 .callout-note collapse="true"}
## Click here to see RES examples illustrating the RES process

We have produced RES for a range of innovations. Many of these are available to read on our website <https://arc-gm.nihr.ac.uk/rapid-evidence-synthesis>.

Below are the RES examples that are frequently referred to in this document. By looking at them, you can see how the steps above have been applied.

·       [Restricting advertising in public spaces](https://arc-gm.nihr.ac.uk/media/Resources/ARC/Evaluation/RES/Implementing%20policies%20that%20restrict%20the%20use%20of%20outdoor%20spaces%20for%20advertising%20harmful%20commodities/ARC-GM%20RES%20outdoor%20advertising%20harmful%20commodities%20revised.pdf)

·       [Managing multiple long-term conditions](https://arc-gm.nihr.ac.uk/media/Resources/ARC/Evaluation/RES/Multiple%20long-term%20conditions/ARC%20RES%20Multiple%20long%20term%20conditions%20-%20final%20report%20(3).pdf)

·       [Integrated Neighbourhood Teams](https://arc-gm.nihr.ac.uk/media/Resources/ARC/Evaluation/RES/UoM%20Healthier%20Futures/UoM%20Healthier%20Futures%20and%20NIHR%20ARC%20GM%20-%20RES%20-%20Integrated%20Neighbourhood%20Teams%20.pdf)

·       [Financial and debt advice in primary care](https://arc-gm.nihr.ac.uk/media/Resources/ARC/Evaluation/RES/Financial%20Hardship%20in%20Primary%20Care/RES%20Financial%20and%20debt%20advice%20in%20primary%20care%20-%20new%20template%20FINAL.pdf)

·       [Remote Spirometry](https://arc-gm.nihr.ac.uk/media/Resources/ARC/Evaluation/RES/Remote%20Spirometry/Remote%20Spirometry%20RES%20-%20new%20template%20FINAL.pdf)

Using the mostly often cited example of [Restricting advertising in public spaces](https://arc-gm.nihr.ac.uk/media/Resources/ARC/Evaluation/RES/Implementing%20policies%20that%20restrict%20the%20use%20of%20outdoor%20spaces%20for%20advertising%20harmful%20commodities/ARC-GM%20RES%20outdoor%20advertising%20harmful%20commodities%20revised.pdf), we describe more details of the key RES steps below that the you can replicate in producing your own RES. This example is relevant if you are commissioned to produce a RES for your commissioners. For users who produce a RES for themselves as the knowledge users, the step of co-producing the RES question with stakeholders may not be applicable.

The RES on [Restricting advertising in public spaces](https://arc-gm.nihr.ac.uk/media/Resources/ARC/Evaluation/RES/Implementing%20policies%20that%20restrict%20the%20use%20of%20outdoor%20spaces%20for%20advertising%20harmful%20commodities/ARC-GM%20RES%20outdoor%20advertising%20harmful%20commodities%20revised.pdf) synthesised research evidence on the implications of implementing government policies to restrict the advertising of harmful commodities in public sector-owned spaces. The Greater Manchester Integrated Care Partnership (GM ICP) Population Health team wanted to use this RES to inform the development of regional policies on this topic.

Through discussion with the GM ICP Population Health team, our first step was to **describe the innovation** that was the focus for this RES:

*‘Outdoor advertising often uses spaces owned by the public sector such as public transport, billboards, and street posters and screens to market unhealthy foods and non-alcoholic beverages (termed as ‘unhealthy food’ hereafter). Exposure to outdoor advertising of unhealthy foods may have adverse impacts on people’s attitudes, preferences, and behaviours towards consuming unhealthy foods, and thus be associated with obesity and non-communicable diseases. People from more disadvantaged groups are considered to have disproportionate exposure to greater food marketing. Implementing government-led policies to decrease the frequency and reach of food advertising and its power (i.e. the persuasive content and strategies used in advertising) have been suggested as a potential way to improve public health.’*

Again via collaborative processes we **formulated the questions** that the RES would seek to answer using the Population, Intervention, Control, Outcome (PICO) framework. As an example, one question was:

*‘What are the implications of implementing government-led policies to restrict advertising of unhealthy foods in public sector-owned spaces \[**Interventions**\] for people of any age \[**participants**\] in terms of advertising outcomes, health outcomes, and financial impact on local authorities \[**outcomes**\]?’*

In line with this question we defined the criteria that we used in deciding which studies were included or excluded:

***Participants:** We included evidence about impacts on people of any age, regardless of existing health conditions. We did not limit the countries where the included studies were conducted, but we considered that the evidence is directly relevant to the context of this RES if the related studies were conducted in the UK.*

***Interventions:** We included evaluations of the impact of any policy that aimed to restrict the advertising of unhealthy foods in public sector-owned spaces …*

***Comparators:** We considered reviews and studies with any comparator group, including no intervention, and alternative interventions.*

***Outcomes:** We included various outcomes which reflect the potential impact of the intervention in four domains …*

In defining the eligibility criteria for **the study design**, we considered evidence synthesis as the primary source of evidence:

***Study design**: In the first instance we considered existing evidence syntheses, including systematic and scoping reviews of any design of primary study. We considered reviews of quantitative, qualitative, and mixed methods research as appropriate to the question addressed. We used a broad definition of systematic reviews as having a systematic search and clear inclusion criteria.*

*Where we were unable to identify relevant, existing evidence syntheses, or where the relevant review evidence was limited, we considered primary studies, looking at the most robust primary study designs first…’*

We **used a highly focused and tailored approach to searching** the literature, in which we searched only two databases that were anticipated to be more relevant:

**Search:** *We searched Medline (Ovid) and the Cochrane Library (including the Cochrane Database of Systematic Reviews and the Cochrane Register of Controlled Trials). Our searches were based on key terms around food and beverage, advertising, and outdoor or public assets. We also searched the reference lists of included reviews and used Google Scholar to identify further related articles.*

We followed the principles of the ROBIS \[12\], a tool for assessing the risk of bias in systematic reviews, to critically **evaluate the validity of the included evidence** and followed the principle of the GRADE approach to assess the certainty of evidence \[11\]. Incorporating the GRADE assessment results, we **summarised the evidence** in relation to the key questions.

**Evidence summary:** *‘There is some limited research evidence regarding the implications of policies that restrict the use of outdoor spaces for advertising alcohol and gambling. We found no research evidence regarding policies to restrict advertising for payday loans.*

*Limited evidence suggests that implementing restrictions on alcohol marketing in outdoor places may reduce the awareness of alcohol advertising in adults, whilst it is uncertain if restricting or banning alcohol advertising could reduce alcohol consumption in adults and adolescents. There is consistent evidence on the causal relationship between exposure to advertising of gambling commodities and positive attitudes towards gambling, intentions to gamble and increased gambling activity.’*
:::

**Describe the innovation** and its purpose. Is it a public health policy, a screening tool, a diagnostic or other test, a service, an organisational change, or something aimed at changing individual behaviours? What alternatives to this innovation exist? What competing alternatives are available that could be used instead (this will include what is being used currently)?  

**Formulate RES questions** based on the key characteristics and aims of the innovation. Consider the PICO(S) approach, which defines the Population, Intervention, Comparator, Outcomes, and Settings (where relevant) criteria that apply.

See the video to learn how to use the PICO framework to formulate a review question.

{{< video https://www.youtube.com/watch?v=7XyOGNliGuE >}}

Where applicable, other frameworks can be followed (see @tbl-1). Initial questions often have a narrow focus to maximise the relevance of the evidence, but you may decide to expand the scope when evidence is sparse (e.g., to wider innovation categories).

+---------------------------+-----------+----------------------------------------------+
| Type of questions         | Framework | Components                                   |
+:==========================+:==========+:=============================================+
| Aetiology                 | PEO       | -   Population                               |
|                           |           | -   Exposure/Environment                     |
|                           |           | -   Outcome                                  |
+---------------------------+-----------+----------------------------------------------+
| Diagnostic test accuracy  | PIRD      | -   Population                               |
|                           |           | -   Index Test                               |
|                           |           | -   Reference Test                           |
|                           |           | -   Diagnosis of Interest                    |
+---------------------------+-----------+----------------------------------------------+
| Treatment                 | PICO      | -   Population                               |
|                           |           |                                              |
|                           |           | -   Intervention                             |
|                           |           |                                              |
|                           |           | -   Comparator                               |
|                           |           |                                              |
|                           |           | -   Outcomes                                 |
+---------------------------+-----------+----------------------------------------------+
| Prognosis                 | PFO       | -   Population                               |
|                           |           |                                              |
|                           |           | -   Prognostic Factor (or model of interest) |
|                           |           |                                              |
|                           |           | -   Outcome                                  |
+---------------------------+-----------+----------------------------------------------+
| Qualitative/Mixed-Methods | SPIDER    | -   Sample                                   |
|                           |           |                                              |
|                           |           | -   Phenomenon of Interest                   |
|                           |           |                                              |
|                           |           | -   Design                                   |
|                           |           |                                              |
|                           |           | -   Evaluation                               |
|                           |           |                                              |
|                           |           | -   Research type                            |
+---------------------------+-----------+----------------------------------------------+
| Scoping                   | PCC       | -   Population                               |
|                           |           |                                              |
|                           |           | -   Concept                                  |
|                           |           |                                              |
|                           |           | -   Context                                  |
+---------------------------+-----------+----------------------------------------------+

: Main frameworks used for facilitating the formulation of review questions {#tbl-1}

**Consider the study design** that offers the most valid and reliable evidence for each question (see @tbl-2). For questions on innovation effectiveness, you can look for and prioritise systematic reviews that include randomised controlled trials (RCTs). In the absence of existing reviews, or if these reviews are limited or dated, you can consider looking for relevant individual studies that have been published more recently, and may adjust the eligibility criteria to encompass a broader range of research evidence if necessary.

**Use a highly focused and tailored approach to searching** the literature. It is recommended that literature searches are developed and conducted with an expert where possible. You can search key sources of evidence, such as the Cochrane Library and Medline databases, and may also refer to additional resources like the National Institute for Health and Care Excellence (NICE) website when relevant. It is required to stringently screen search results based on pre-established eligibility criteria set out in the protocol (i.e., ‘rules to apply’ when deciding whether to include or exclude articles).

**Extract the relevant information and evaluate evidence validity and certainty.** Relevant information needs to be taken from the selected material, including findings and any relevant assessment of validity and certainty. These assessments are often guided by tools such as the Cochrane tool for assessing the risk of bias in RCTs \[9\] and the ROBINS-I tool for non-RCT evidence \[10\]. The GRADE approach is widely used for assessing the certainty of a body of evidence \[11\]. These judgements provide a sense of how confident we can be in the research findings. Where existing evidence has not previously had its validity or certainty assessed, you as the RES reviewers may perform the relevant assessments as needed. Additionally, at this stage it is vital for you to consider the relevance of the evidence to the local context in terms of service model, comparators and populations.

**Synthesising and summarising the evidence** to answer the key questions. It is strongly recommended to present a clear summary of findings, including a judgement of how confident we can be in them. This is to explain the nature of any uncertainty in the evidence, and how relevant it is to the key questions.

Beyond the synthesis of evidence per se, you may also consider preparing the groundwork for further evaluation (e.g., questions that should be addressed in proof-of-value or deployment at scale), co-working with partners.

Further information about our approach is detailed in our [journal publication](https://systematicreviewsjournal.biomedcentral.com/articles/10.1186/s13643-022-02106-z).

## Section summary

The ARC-GM has developed a rapid evidence synthesis (RES) approach. The RES approach draws on evidence synthesis methods and decision frameworks and provides rapid assessments of existing evidence and its relevance to specific local decision problems.

The ARC-GM regards RES as a suitable alternative to full evidence synthesis in certain situations. RES serves local decision-makers who need a summary of the best available evidence to support timely decision-making on innovation adoption (or de-implementation). It is not always appropriate, feasible or necessary to conduct a RES.

## Tasks to complete

☐ Decide whether a RES is appropriate and feasible for the question you want to answer

☐ Collaborate with your partners, if applicable
