# Presenting and communicating findings

In this section, we consider ways of presenting information in the RES to maximise understanding of the findings and their implications.

## Learning objectives

By the end of this section, you should:

·       Understand how to write RES reports using clear and accessible language

## Producing accessible RES reports for knowledge mobilisation

The target audience for a RES is normally policy- or decision-makers who are frequently not research or evidence synthesis experts. The readability of a RES is important. We outline key factors that we believe will make a RES accessible and user-friendly.

**Clear summaries with user-friendly language and formatting:** We always provide a summary of the evidence for each key question(s), even when little or no (useful) evidence is identified (@nte-5). Each question is addressed separately. Where possible, we summarise existing evidence as a narrative synthesis as detailed in Section 5 with an assessment of certainty and relevance.

 We try to present the findings of a RES:

-   Using simple language, free of jargon and technical language wherever possible;

·       Where using technical terms cannot be avoided, provide explanations in simple language;

-   Using easy-to-understand statistical information;

-   Using visual elements to complement text, such as tables and figures;

·       Using an easy-to-follow layout with subheadings, bullet points, and a consistent style.

**Concise reporting**: We usually begin a RES with a 1 to 2 page summary of the main findings, in order to communicate the questions and answers upfront. This summary is followed by the full report which is typically 10 to 20 pages in length. See the examples in @nte-2. We refer you to the very useful Cochrane [guidance](https://training.cochrane.org/system/files/uploads/protected_file/GUIDAN~1.PDF#page=8) on writing a plain language summary along with their [template](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.cochrane.org%2Fauthors%2Fhandbooks-and-manuals%2Fhandbook%2Fcurrent%2Ftemplate-writing-cochrane-plain-language-summary.docx&wdOrigin=BROWSELINK).

**Objective tone**: A RES presents evidence that helps decision-makers make informed choices about adopting and implementing innovations. The report should be written in an objective tone, focusing solely on the evidence itself. We refrain from making recommendations about whether to adopt or reject an innovation or intervention because we believe that research evidence is only one piece of information that needs to be considered in decision-making.

## Section summary

A RES report often begins with a 1–2 page summary, followed by a full report of 10–20 pages.

We present RES findings using clear, plain language and try to keep reports concise.

## Tasks to complete

☐ Write up a RES report, referring to [examples](https://arc-gm.nihr.ac.uk/rapid-evidence-synthesis) of RES reports

☐ Write a Summary section in a RES report, referring to the Cochrane plain language summary [template](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.cochrane.org%2Fauthors%2Fhandbooks-and-manuals%2Fhandbook%2Fcurrent%2Ftemplate-writing-cochrane-plain-language-summary.docx&wdOrigin=BROWSELINK) and [guidance](https://training.cochrane.org/system/files/uploads/protected_file/GUIDAN~1.PDF#page=8)

☐ Check the readability of the RES report
